# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django.core.validators
import django.contrib.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default=b'avatar/default.png', upload_to=b'avatar/%Y/%m', max_length=200, blank=True, null=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\xa4\xb4\xe5\x83\x8f')),
                ('qq', models.CharField(max_length=20, null=True, verbose_name=b'QQ\xe5\x8f\xb7\xe7\xa0\x81', blank=True)),
                ('mobile', models.CharField(max_length=11, unique=True, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81', blank=True)),
                ('groups', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Group', blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Permission', blank=True, help_text='Specific permissions for this user.', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('license_plate', models.CharField(max_length=64, verbose_name=b'\xe8\xbd\xa6\xe7\x89\x8c\xe5\x8f\xb7\xe7\xa0\x81')),
                ('car_owner', models.CharField(max_length=64, verbose_name=b'\xe8\xbd\xa6\xe4\xb8\xbb')),
                ('registration_location', models.CharField(max_length=32, verbose_name=b'\xe8\xbd\xa6\xe8\xbe\x86\xe6\xb3\xa8\xe5\x86\x8c\xe5\x9c\xb0\xe7\x82\xb9')),
                ('vehicle_type', models.CharField(max_length=32, verbose_name=b'\xe8\xbd\xa6\xe8\xbe\x86\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('body_color', models.CharField(max_length=32, verbose_name=b'\xe8\xbd\xa6\xe8\xba\xab\xe9\xa2\x9c\xe8\x89\xb2')),
                ('weight', models.IntegerField(verbose_name=b'\xe6\xa0\xb8\xe5\xae\x9a\xe9\x87\x8d\xe9\x87\x8f')),
                ('date_of_inspection', models.BigIntegerField(verbose_name=b'\xe5\xb9\xb4\xe5\xae\xa1\xe6\x97\xa5\xe6\x9c\x9f')),
                ('record_date', models.BigIntegerField(verbose_name=b'\xe7\x99\xbb\xe8\xae\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('busload', models.IntegerField(verbose_name=b'\xe6\xa0\xb8\xe5\xae\x9a\xe8\xbd\xbd\xe5\xae\xa2\xe4\xbd\x8d')),
                ('labelnumber', models.CharField(max_length=64, verbose_name=b'\xe8\xbd\xa6\xe8\xbe\x86\xe5\x8e\x82\xe7\x89\x8c')),
                ('transportcertificate', models.CharField(max_length=64, verbose_name=b'\xe8\xbf\x90\xe8\xbe\x93\xe8\xaf\x81\xe5\xad\x97\xe5\x8f\xb7')),
                ('tcissuingauthority', models.CharField(max_length=64, verbose_name=b'\xe8\xbf\x90\xe8\xbe\x93\xe8\xaf\x81\xe5\x8f\x91\xe8\xaf\x81\xe6\x9c\xba\xe6\x9e\x84')),
                ('enginenumber', models.CharField(max_length=64, verbose_name=b'\xe5\x8f\x91\xe5\x8a\xa8\xe6\x9c\xba\xe5\x8f\xb7')),
                ('vinnumber', models.CharField(max_length=64, verbose_name=b'\xe8\xbd\xa6\xe8\xbe\x86VIN\xe7\xa0\x81')),
                ('fueltype', models.CharField(max_length=64, verbose_name=b'\xe8\xbd\xa6\xe8\xbe\x86\xe7\x87\x83\xe6\x96\x99\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('displacement', models.FloatField(verbose_name=b'\xe5\x8f\x91\xe5\x8a\xa8\xe6\x9c\xba\xe6\x8e\x92\xe9\x87\x8f')),
                ('insurancecompany', models.CharField(max_length=64, verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe5\x85\xac\xe5\x8f\xb8')),
                ('insurancenumber', models.CharField(max_length=64, verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe5\x8f\xb7')),
                ('insurancetype', models.CharField(max_length=64, verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('insuranceamount', models.FloatField(max_length=64, verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe9\x87\x91\xe9\xa2\x9d')),
                ('insuranceeffectivedate', models.BigIntegerField(verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe7\x94\x9f\xe6\x95\x88\xe6\x97\xa5\xe6\x9c\x9f')),
                ('insuranceexpirationdate', models.BigIntegerField(verbose_name=b'\xe4\xbf\x9d\xe9\x99\xa9\xe5\x88\xb0\xe6\x9c\x9f\xe6\x97\xa5\xe6\x9c\x9f')),
                ('totalmileage', models.IntegerField(verbose_name=b'\xe8\xa1\x8c\xe9\xa9\xb6\xe6\x80\xbb\xe9\x87\x8c\xe7\xa8\x8b')),
                ('bounddevice', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x91\xe5\xae\x9a\xe7\x9a\x84\xe8\xae\xbe\xe5\xa4\x87')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u8f66\u8f86\u4fe1\u606f',
                'verbose_name_plural': '\u8f66\u8f86\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Deviceinfohis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('device_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xbc\x96\xe5\x8f\xb7')),
                ('serial_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('order_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('division_number', models.CharField(max_length=64, verbose_name=b'\xe8\xa1\x8c\xe6\x94\xbf\xe5\x8c\xba\xe5\x88\x92\xe7\xbc\x96\xe5\x8f\xb7')),
                ('time', models.BigIntegerField(verbose_name=b'\xe5\xae\x9a\xe4\xbd\x8d\xe6\x97\xb6\xe9\x97\xb4')),
                ('longitude', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x8f\xe5\xba\xa6')),
                ('latitude', models.CharField(max_length=64, verbose_name=b'\xe7\xba\xac\xe5\xba\xa6')),
                ('speed', models.FloatField(verbose_name=b'\xe7\x9e\xac\xe6\x97\xb6\xe9\x80\x9f\xe5\xba\xa6')),
                ('altitude', models.FloatField(verbose_name=b'\xe6\xb5\xb7\xe6\x8b\x94\xe9\xab\x98\xe5\xba\xa6')),
                ('direction_angle', models.CharField(max_length=64, verbose_name=b'\xe6\x96\xb9\xe5\x90\x91\xe8\xa7\x92')),
                ('management_status', models.CharField(max_length=32, verbose_name=b'\xe7\xbb\x8f\xe8\x90\xa5\xe7\x8a\xb6\xe6\x80\x81')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u8bbe\u5907\u5de5\u4f5c\u5386\u53f2\u4fe1\u606f',
                'verbose_name_plural': '\u8bbe\u5907\u5de5\u4f5c\u5386\u53f2\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Deviceinforeal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('device_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xbc\x96\xe5\x8f\xb7')),
                ('serial_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('order_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('division_number', models.CharField(max_length=64, verbose_name=b'\xe8\xa1\x8c\xe6\x94\xbf\xe5\x8c\xba\xe5\x88\x92\xe7\xbc\x96\xe5\x8f\xb7')),
                ('time', models.BigIntegerField(verbose_name=b'\xe5\xae\x9a\xe4\xbd\x8d\xe6\x97\xb6\xe9\x97\xb4')),
                ('longitude', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x8f\xe5\xba\xa6')),
                ('latitude', models.CharField(max_length=64, verbose_name=b'\xe7\xba\xac\xe5\xba\xa6')),
                ('speed', models.FloatField(verbose_name=b'\xe7\x9e\xac\xe6\x97\xb6\xe9\x80\x9f\xe5\xba\xa6')),
                ('altitude', models.FloatField(verbose_name=b'\xe6\xb5\xb7\xe6\x8b\x94\xe9\xab\x98\xe5\xba\xa6')),
                ('direction_angle', models.CharField(max_length=64, verbose_name=b'\xe6\x96\xb9\xe5\x90\x91\xe8\xa7\x92')),
                ('management_status', models.CharField(max_length=32, verbose_name=b'\xe7\xbb\x8f\xe8\x90\xa5\xe7\x8a\xb6\xe6\x80\x81')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u8bbe\u5907\u5de5\u4f5c\u5b9e\u65f6\u4fe1\u606f',
                'verbose_name_plural': '\u8bbe\u5907\u5de5\u4f5c\u5b9e\u65f6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('avatar', models.ImageField(default=b'driver/default.png', upload_to=b'driver/%Y/%m', max_length=200, blank=True, null=True, verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\xa4\xb4\xe5\x83\x8f')),
                ('owned_company', models.CharField(max_length=64, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x85\xac\xe5\x8f\xb8')),
                ('identifier', models.CharField(max_length=64, verbose_name=b'\xe5\x8f\xb8\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\xa7\x93\xe5\x90\x8d')),
                ('license_number', models.CharField(max_length=24, verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe8\xaf\x81\xe5\x8f\xb7')),
                ('gender', models.NullBooleanField(verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('nationality', models.CharField(max_length=32, verbose_name=b'\xe5\x9b\xbd\xe7\xb1\x8d')),
                ('birth', models.BigIntegerField(verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe6\x97\xa5\xe6\x9c\x9f')),
                ('quasi_car_type', models.CharField(max_length=8, verbose_name=b'\xe5\x87\x86\xe9\xa9\xbe\xe8\xbd\xa6\xe5\x9e\x8b')),
                ('issue_date', models.BigIntegerField(verbose_name=b'\xe5\x88\x9d\xe6\xac\xa1\xe9\xa2\x86\xe8\xaf\x81\xe6\x97\xa5\xe6\x9c\x9f')),
                ('valid_date', models.BigIntegerField(verbose_name=b'\xe6\x9c\x89\xe6\x95\x88\xe6\x97\xa5\xe6\x9c\x9f')),
                ('phone_number', models.CharField(max_length=64, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d\xe5\x8f\xb7\xe7\xa0\x81')),
                ('nation', models.CharField(max_length=32, verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe6\xb0\x91\xe6\x97\x8f')),
                ('maritalstatus', models.NullBooleanField(verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\xa9\x9a\xe5\xa7\xbb\xe7\x8a\xb6\xe5\x86\xb5')),
                ('car_info', models.CharField(max_length=64, verbose_name=b'\xe6\x89\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe8\xbd\xa6\xe7\x89\x8c\xe5\x8f\xb7\xe7\xa0\x81')),
                ('driverdegree', models.CharField(max_length=32, verbose_name=b'\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\xad\xa6\xe5\x8e\x86')),
                ('cruisedrivers', models.NullBooleanField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xa1\xe6\xb8\xb8\xe5\x87\xba\xe7\xa7\x9f\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98')),
                ('certificationauthority', models.CharField(max_length=64, verbose_name=b'\xe5\x8f\x91\xe8\xaf\x81\xe6\x9c\xba\xe6\x9e\x84')),
                ('qualificatcertificatdate', models.BigIntegerField(verbose_name=b'\xe8\xb5\x84\xe6\xa0\xbc\xe5\x8f\x91\xe8\xaf\x81\xe6\x97\xa5\xe6\x9c\x9f')),
                ('qualificatvaliditydate', models.BigIntegerField(verbose_name=b'\xe8\xb5\x84\xe6\xa0\xbc\xe6\x9c\x89\xe6\x95\x88\xe6\x9c\x9f\xe6\xad\xa2')),
                ('trainingcoursename', models.CharField(max_length=64, verbose_name=b'\xe5\x9f\xb9\xe8\xae\xad\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('trainingstarttime', models.BigIntegerField(verbose_name=b'\xe5\x9f\xb9\xe8\xae\xad\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('trainingendtime', models.BigIntegerField(verbose_name=b'\xe5\x9f\xb9\xe8\xae\xad\xe7\xbb\x93\xe6\x9d\x9f\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('lengthoftraining', models.FloatField(verbose_name=b'\xe5\x9f\xb9\xe8\xae\xad\xe6\x97\xb6\xe9\x95\xbf')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u9a7e\u9a76\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u9a7e\u9a76\u5458\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Imagedevice',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('device_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xbc\x96\xe5\x8f\xb7')),
                ('serial_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('order_number', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('carimage', models.ImageField(default=b'imagedevice/default.png', upload_to=b'imagedevice/%Y/%m', max_length=200, blank=True, null=True, verbose_name=b'\xe8\xbd\xa6\xe5\x86\x85\xe7\x85\xa7\xe7\x89\x87')),
                ('time', models.BigIntegerField(verbose_name=b'\xe6\x8b\x8d\xe7\x85\xa7\xe6\x97\xb6\xe9\x97\xb4')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u8f66\u5185\u62cd\u7167\u4fe1\u606f',
                'verbose_name_plural': '\u8f66\u5185\u62cd\u7167\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Netcarcompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('companyname', models.CharField(max_length=64, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('uniformsocialcreditcode', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x9f\xe4\xb8\x80\xe7\xa4\xbe\xe4\xbc\x9a\xe4\xbf\xa1\xe7\x94\xa8\xe4\xbb\xa3\xe7\xa0\x81')),
                ('registrydivisions', models.CharField(max_length=64, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe5\x9c\xb0\xe8\xa1\x8c\xe6\x94\xbf\xe5\x8c\xba\xe5\x88\x92')),
                ('economicoperationtype', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x8f\xe8\x90\xa5\xe4\xb8\x9a\xe6\x88\xb7\xe7\xbb\x8f\xe6\xb5\x8e\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('registeredcapital', models.IntegerField(verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe8\xb5\x84\xe6\x9c\xac')),
                ('legalrepresentative', models.CharField(max_length=64, verbose_name=b'\xe6\xb3\x95\xe4\xba\xba\xe4\xbb\xa3\xe8\xa1\xa8')),
                ('legalpersonidentification', models.CharField(max_length=24, verbose_name=b'\xe6\xb3\x95\xe4\xba\xba\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7')),
                ('phone_number', models.CharField(max_length=64, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d\xe5\x8f\xb7\xe7\xa0\x81')),
                ('address', models.CharField(max_length=64, verbose_name=b'\xe9\x80\x9a\xe8\xae\xaf\xe5\x9c\xb0\xe5\x9d\x80')),
                ('businessscope', models.CharField(max_length=256, verbose_name=b'\xe7\xbb\x8f\xe8\x90\xa5\xe8\x8c\x83\xe5\x9b\xb4')),
                ('managementarea', models.CharField(max_length=64, verbose_name=b'\xe7\xbb\x8f\xe8\x90\xa5\xe5\x8c\xba\xe5\x9f\x9f')),
                ('businessname', models.CharField(max_length=64, verbose_name=b'\xe4\xb8\x9a\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('certificationauthority', models.CharField(max_length=64, verbose_name=b'\xe5\x8f\x91\xe8\xaf\x81\xe6\x9c\xba\xe6\x9e\x84')),
                ('issuedate', models.BigIntegerField(verbose_name=b'\xe5\x8f\x91\xe8\xaf\x81\xe6\x97\xa5\xe6\x9c\x9f')),
                ('validitydate', models.BigIntegerField(verbose_name=b'\xe6\x9c\x89\xe6\x95\x88\xe6\x9c\x9f\xe6\xad\xa2')),
                ('licensestatus', models.CharField(max_length=32, verbose_name=b'\xe8\xaf\x81\xe7\x85\xa7\xe7\x8a\xb6\xe6\x80\x81')),
                ('platformcarnumber', models.BigIntegerField(verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe6\xb3\xa8\xe5\x86\x8c\xe7\xbd\x91\xe7\xba\xa6\xe8\xbd\xa6\xe8\xbe\x86\xe6\x95\xb0')),
                ('platformdrivernumber', models.BigIntegerField(verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0\xe6\xb3\xa8\xe5\x86\x8c\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe6\x95\xb0')),
                ('updatedate', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u7f51\u7ea6\u8f66\u5e73\u53f0\u4fe1\u606f',
                'verbose_name_plural': '\u7f51\u7ea6\u8f66\u5e73\u53f0\u4fe1\u606f',
            },
        ),
    ]
